version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '4001:4001'
    environment:
      - RIOT_API_KEY=${RIOT_API_KEY}
      - PORT=4001

  frontend:
    build: ./frontend
    ports:
      - '3001:80'
    depends_on:
      - server
