version: '3.8'

services:
  # Servicio Principal - Backend + Frontend integrados
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flyquest-app
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
    env_file:
      - ./server/.env
    volumes:
      # Persistir datos de bugs y logs
      - app-data:/app/server/data
      - app-logs:/app/logs
    restart: unless-stopped
    networks:
      - flyquest-network
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4001/api/mantenimiento/estado" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Volúmenes nombrados para persistencia de datos
volumes:
  app-data:
    driver: local
  app-logs:
    driver: local

# Red personalizada para comunicación entre servicios
networks:
  flyquest-network:
    driver: bridge
