version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '4000:4000'
    environment:
      - RIOT_API_KEY=${RIOT_API_KEY}

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - server
