services:
  # Backend API Server
  - type: web
    name: flyquest-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001
    healthCheckPath: /api/flyquest/matches

  # Frontend (Static Site)
  - type: web
    name: flyquest-frontend
    runtime: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://flyquest-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
